ibm_cloud_fail_over/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
ibm_cloud_fail_over/ibm_cloud_fail_over.py,sha256=B6zNVuUynNqfFyxg0g8dVXRkNdpruDlhcxXbtxR-IaU,21707
ibm_cloud_fail_over-0.0.3.dist-info/METADATA,sha256=9Zp-uux9p4poHhXhf0jvsZSJYycZKc_e8vPkSlQq7Dk,5260
ibm_cloud_fail_over-0.0.3.dist-info/WHEEL,sha256=C2FUgwZgiLbznR-k0b_5k3Ai_1aASOXDss3lzCUsUug,87
ibm_cloud_fail_over-0.0.3.dist-info/licenses/LICENSE,sha256=xx0jnfkXJvxRnG63LTGOxlggYnIysveWIZ6H3PNdCrQ,11357
ibm_cloud_fail_over-0.0.3.dist-info/RECORD,,
